### ISSUE TITLE
litemap:  astLib - fits import issue

### ISSUE THREAD

**Issue by ajvanengelen** [ACTCollaboration/flipper#18]
I'm posting this issue on behalf of Connor Sheere, a student working with me, Joel M, and Renee H.  This is apparently an issue with the astWCS package and I'm not sure whether this is related to the pyFITS / astropi.io.fits switchover, it seems to be a separate thing

Is astLib.astWCS one of the formal requirements for this package?

/home/csheere/.local/lib/python2.7/site-packages/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/mnt/raid-cita/csheere/2017rSummer/lenspower/py/testQuadrupoleNoise.py in <module>()
     14 import numpy
     15 import os
---> 16 import mapForecastingTools
     17 import computeTauPower
     18 

/mnt/raid-cita/csheere/2017rSummer/lenspower/py/mapForecastingTools.py in <module>()
      3 import sys
      4 # sys.path.append('../flipper/flipper')
----> 5 import flipper.liteMap
      6 #import flipper
      7 # sys.path.append('../flipperPol/flipperPol')

/mnt/raid-cita/csheere/2017rSummer/lenspower/flipper/flipper/liteMap.py in <module>()
     17 
     18 import astLib
---> 19 from astLib import astWCS
     20 from astLib import astCoords
     21 from utils import *

/home/csheere/.local/lib/python2.7/site-packages/astLib/astWCS.py in <module>()
     26 
     27 from astropy.io import fits as pyfits
---> 28 from PyWCSTools import wcs
     29 import numpy
     30 import locale

/home/csheere/.local/lib/python2.7/site-packages/PyWCSTools/wcs.py in <module>()
     24                 fp.close()
     25             return _mod
---> 26     _wcs = swig_import_helper()
     27     del swig_import_helper
     28 else:

/home/csheere/.local/lib/python2.7/site-packages/PyWCSTools/wcs.py in swig_import_helper()
     20         if fp is not None:
     21             try:
---> 22                 _mod = imp.load_module('_wcs', fp, pathname, description)
     23             finally:
     24                 fp.close()

ImportError: /home/csheere/.local/lib/python2.7/site-packages/PyWCSTools/_wcs.so: undefined symbol: __intel_sse2_strcpy

**Comment by cgrays** [comment]
astLib version is 0.10.2

**Comment by dwhan89** [comment]
I have seen this error before, but in a different context that is unrelated to astLib.

`ImportError: /home/csheere/.local/lib/python2.7/site-packages/PyWCSTools/_wcs.so: undefined symbol: __intel_sse2_strcpy`

I think the error message above is indicating that something went wrong with astWCS compilation. I will check by trying to import astWCS directly, and check whether it gives the same error message.

**Comment by msyriac** [comment]
I think this happens if you mix compilers. Maybe reinstall astLib after making sure you only have gcc loaded?

**Comment by cgrays** [comment]
Right, sorry. This worked.
Thanks!
