### ISSUE TITLE
do we need pyfits?

### ISSUE THREAD

**Issue by ajvanengelen** [ACTCollaboration/flipper#19]
Has the pyfits dependence of flipper been completely removed from the code?  The reason I ask is that my pip installation of flipper on niagara.scinet.utoronto.ca hit an inscrutible snag when it tried to install pyfits, but this was evidently cleared up when I removed pyfits from the required packages here: https://github.com/ACTCollaboration/flipper/blob/f4d215109e1300d679645e5df582add76b6d54f3/setup.py#L14

**Comment by msyriac** [comment]
As far as I can see, we have no pyfits dependence. The setup.py does indeed need to be updated.
